### ISSUE TITLE
Makefile Invalid - Not including headers correctly

### ISSUE THREAD

**Issue by kishore-ganesh** [danielpinto8zz6/c-cpp-project-generator#134]
**Describe the bug**
Header files in include/ not found.

**To Reproduce**
1. Create C++ project
2. Create file test.h in include/
3. Create file test.cpp in src/
4. Include test.h in test.cpp
5. Add any driver code
6. Run make on directory root

**Expected behavior**
On running make, the files should get compiled

**Resultant Behavior:**
Make complains that it can't find header file.
**Environment**
 - VSCode Version: 1.45.1
 - OS Version: Linux Mint 

**Additional context**
I believe this is because of the use of implicit rules where the -I flag is not passed for include directories. This can be fixed by adding $(CINCLUDES) to $(CPPFLAGS).

**Comment by danielpinto8zz6** [comment]
Put your header files in include folder

**Comment by kishore-ganesh** [comment]
The header files were in the include folder only.

**Comment by denvolj** [comment]
Same problem, fixed in referenced commit.

**Environment**
- OS: Ubuntu 20.04
- VSCode: 1.46.0

Make trying to compile sources without parameters (between g++ and -c is 4 whitespaces):
`g++    -c -o src/utils.o src/utils.cpp`

Attemt to change the CC variable doesn't affects result. I tried `CC := alsdkjf` but command string remains same.

Seems make uses default compilation template or something when trying to compile object by default.

If my solution is rough or I was wrong, please correct me.

**Comment by danielpinto8zz6** [comment]
you're welcome to create a pull request :+1:

**Comment by denvolj** [comment]
Done.

**Comment by binarymaker** [comment]
How to include header files in different folders? 

I have project in below structure. 
![issu](https://user-images.githubusercontent.com/45413608/87575626-cef60580-c6ed-11ea-90d4-6a0262cb0837.PNG)

 issue is `print.h` file can't find in main.c

```c
/* file: main.c */
#include <stdio.h>
#include "print.h"

int main()
{
	for(int i = 0; i < 10; i++)
	{
		print_hello();
	}
	return (0);
}
```
i am not like to include by path, it makes code unportable and ugly.

thanks, you done great job

**Comment by danielpinto8zz6** [comment]
print.h should be in include, print.c in src
